services:
  app:
    image: ghcr.io/ZuBeri05/chatgpt2api:latest
    container_name: chatgpt2api
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json:ro
